export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS";
export const PRODUCT_FAILS = "PRODUCT_FAILS";


export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAIL_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAIL_SUCCESS";
export const PRODUCT_DETAILS_FAILS = "PRODUCT_DETAIL_FAILS";